version: "3"

services:
  nginx:
    build:
      context: ./docker/dev/nginx
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
      - ./docker/dev/nginx/logs:/var/log/nginx
    ports:
      # Nuxt port
      - 8080:80
      # Laravel port
      - 8081:81
    depends_on:
      - laravel_blog-backend
      - nuxt-frontend
  laravel_blog-backend:
    build:
      #    ./laravel_blog-backend/
      context: docker/dev/laravel_blog-backend
      dockerfile: Dockerfile
    #    ports:
    #      - 8000:8000
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
      TZ: Europe/Moscow
    volumes:
      - ./laravel_blog-backend:/var/www/laravel_blog-backend
  nuxt-frontend:
    build:
      #    ./nuxt-frontend/
      context: docker/dev/nuxt-frontend
      dockerfile: Dockerfile
    #    ports:
    #      - 3000:3000
    volumes:
      - ./nuxt-frontend/:/var/www

  # PostgreSQL database container
  postgres:
    build:
      context: docker/dev/postgres
      dockerfile: Dockerfile
    volumes:
      # Database volume
      - database:/var/lib/postgresql/data
      # Temp volume to allow using dumps
      - ./docker/dev/postgres/dumps/:/tmp/
    ports:
      - 54321:5432
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app

########## Volumes ###################################

volumes:
  database:
    driver: local
#  redis:
#    driver: local